language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
  - master
  - tip

os:
  - linux
  - osx

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade && brew install yarn; fi

script:
  - cd dnsfilter && go get -d -t . && go test
  - cd ../coredns_plugin && go get -d -t . && go test
  - cd .. && make

