language: go
sudo: false
go:
  - 1.11.x
  - 1.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod
    - $HOME/Library/Caches/go-build

os:
  - linux
  - osx

install:
  - npm --prefix client install

script:
  - go test ./...
  - make

