language: go
sudo: false
go:
  - 1.10.x
  - 1.11.x
  - 1.x

os:
  - linux
  - osx

install:
  - go get -v -d -t ./...
  - npm --prefix client install

script:
  - (cd `go env GOPATH`/src/github.com/prometheus/client_golang && git checkout -q v0.8.0)
  - go test ./...
  - make

