%YAML 1.2
---
# https://docs.docker.com/compose/compose-file/

version: '2.4'

services:

  adguard-home:
    image: adguard/adguardhome:armhf-latest
    init: true
    ports:
    - "53:53/tcp"
    - "53:53/udp"
    - "67:67/tcp"
    - "67:67/udp"
    - "68:68/tcp"
    - "68:68/udp"
    - "80:80/tcp"
    - "443:443/tcp"
    - "853:853/tcp"
    - "853:853/udp"
    - "3000:3000/tcp"
    volumes:
    - /opt/adguard-home:/opt/adguardhome/conf
    - /srv/adguard-home:/opt/adguardhome/work
    #user: nobody
    read_only: true
    restart: always

...
